/*const judul = document.getElementById('judul');
judul.style.color = 'blue';
judul.style.backgroundColor = 'yellow';

const h1 = document.getElementsByTagName('h1')[0];
h1.style.fontsize = '50px';

const p = document.getElementsByTagName('p');
for ( var i = 0; i < p.length; i++) {
    p[i].style.backgroundColor ='#dedede';
}

const p2 = document.getElementsByClassName('p2')[0];
p2.innerHTML = 'ini di ubah tanpa menyentuh html';*/

/*const p4 = document.querySelector('#b p');
p4.style.color = 'yellow';

const li2 = document.querySelector('section#b ul li:nth-child(2)');
li2.style.backgroundColor = 'orange';

const p = document.querySelectorAll('p');
for (let i = 0; i < p.length; i++) {
    p[i].style.backgroundColor = 'lightblue';
}*/

const sectionb = document.querySelector('section#b');
const p4 = sectionb.getElementsByTagName('p')[0];
p4.style.color = 'orange';


